In [33]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.model_selection import train_test_split 
from sklearn.metrics import r2_score 

import pandas as pd 
import numpy as np

In [7]:
from sklearn.datasets import load_diabetes

data = load_diabetes() 
df = pd.DataFrame(data.data,columns = data.feature_names)

In [8]:
df.head()

        age       sex       bmi        bp        s1        s2        s3        s4        s5        s6
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401 -0.002592  0.019907 -0.017646
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412 -0.039493 -0.068332 -0.092204
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356 -0.002592  0.002861 -0.025930
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038  0.034309  0.022688 -0.009362
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142 -0.002592 -0.031988 -0.046641

In [10]:
df['target'] = data.target

In [11]:
df.head()

        age       sex       bmi        bp        s1        s2        s3        s4        s5        s6  target
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401 -0.002592  0.019907 -0.017646   151.0
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412 -0.039493 -0.068332 -0.092204    75.0
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356 -0.002592  0.002861 -0.025930   141.0
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038  0.034309  0.022688 -0.009362   206.0
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142 -0.002592 -0.031988 -0.046641   135.0

# Simple Linear Regression

In [24]:
X_train,X_test,y_train,y_test = train_test_split(
    df.iloc[:,:-1],df.iloc[:,-1:],test_size = 0.2, random_state= 42)

In [26]:
X_train.shape,X_test.shape

((353, 10), (89, 10))

In [28]:
lr = LinearRegression()
lr.fit(X_train,y_train) 

y_predlr = lr.predict(X_test)

r2_score(y_test,y_predlr)

0.4526027629719197

# Ridge Regression

In [31]:
rg = Ridge(alpha = 0.1) 
rg.fit(X_train,y_train) 

y_predrg = rg.predict(X_test) 

r2_score(y_test,y_predrg)

0.46085219464119254

# Lasso Regression

In [32]:
lo = Lasso(alpha = 0.1) 
lo.fit(X_train,y_train) 

y_predlo = lo.predict(X_test)

r2_score(y_test,y_predlo)

0.4718547867276227

# ElasticNet Regression

In [54]:
en = ElasticNet(alpha = 0.0009,l1_ratio = 0.5) 
en.fit(X_train,y_train) 

y_preden = en.predict(X_test)  

r2_score(y_test, y_preden)

0.4615169225242016