In [1]:
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

import pandas as pd 
import numpy as np

# For Binary Classification

In [4]:
df_one = pd.read_csv('placement_class.csv')
df_one.head()

   Unnamed: 0  cgpa   iq  placement
0           0   6.8  123          1
1           1   5.9  106          0
2           2   5.3  121          0
3           3   7.4  132          1
4           4   5.8  142          0

In [7]:
df_one.drop((df_one.columns[0]), axis = 1, inplace= True)

In [8]:
df_one.head()

   cgpa   iq  placement
0   6.8  123          1
1   5.9  106          0
2   5.3  121          0
3   7.4  132          1
4   5.8  142          0

In [9]:
df_one.shape

(100, 3)

In [20]:
from sklearn.model_selection import train_test_split 

X_train,X_test,y_train,y_test = train_test_split(df_one.iloc[:,:2],df_one.iloc[:,-1:], test_size= 0.4, random_state= 42)

In [21]:
lor = LogisticRegression() 
lor.fit(X_train,y_train)

y_predlr = lor.predict(X_test)

C:\Users\HP Laptop 15\tfenv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [33]:
dt = DecisionTreeClassifier() 
dt.fit(X_train,y_train)

y_preddt = dt.predict(X_test)

In [34]:
print(accuracy_score(y_test,y_predlr))

print(accuracy_score(y_test,y_preddt))

0.9
0.925

In [35]:
print(classification_report(y_test,y_predlr))
print(classification_report(y_test,y_preddt))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89        18
           1       0.95      0.86      0.90        22

    accuracy                           0.90        40
   macro avg       0.90      0.90      0.90        40
weighted avg       0.90      0.90      0.90        40

              precision    recall  f1-score   support

           0       0.86      1.00      0.92        18
           1       1.00      0.86      0.93        22

    accuracy                           0.93        40
   macro avg       0.93      0.93      0.92        40
weighted avg       0.94      0.93      0.93        40

In [36]:
print(confusion_matrix(y_test,y_predlr))
print(confusion_matrix(y_test,y_preddt))

[[17  1]
 [ 3 19]]
[[18  0]
 [ 3 19]]

# For 3-class Dataset

In [25]:
import seaborn as sns 

df_two = sns.load_dataset('iris')

In [26]:
df_two.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [28]:
from sklearn.preprocessing import LabelEncoder 

encoder = LabelEncoder() 
df_two['species'] = encoder.fit_transform(df_two['species'])

In [31]:
df_two.tail(3)

     sepal_length  sepal_width  petal_length  petal_width  species
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

In [37]:
X_train1,X_test1, y_train1, y_test1 = train_test_split(df_two.iloc[:,:4],df_two.iloc[:,-1:], test_size= 0.3, random_state= 42)

In [38]:
lor1 = LogisticRegression(multi_class= 'multinomial')
lor1.fit(X_train1,y_train1)

C:\Users\HP Laptop 15\tfenv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP Laptop 15\tfenv\lib\site-packages\sklearn\linear_model\_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='multinomial')

In [39]:
y_predlr1 = lor1.predict(X_test1)

In [41]:
dt1 = DecisionTreeClassifier() 
dt1.fit(X_train1,y_train1) 

y_preddt1 = dt1.predict(X_test1)

In [42]:
print(classification_report(y_test1,y_predlr1))

print(classification_report(y_test1,y_preddt1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [43]:
print(confusion_matrix(y_test1,y_predlr1))         
print(confusion_matrix(y_test1, y_preddt1))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

# 10 Classes

In [44]:
df_three = pd.read_csv('mnist_train.csv')

In [45]:
df_three.head()

   label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  ...  28x20  28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28
0      5    0    0    0    0    0    0    0    0  ...      0      0      0      0      0      0      0      0      0
1      0    0    0    0    0    0    0    0    0  ...      0      0      0      0      0      0      0      0      0
2      4    0    0    0    0    0    0    0    0  ...      0      0      0      0      0      0      0      0      0
3      1    0    0    0    0    0    0    0    0  ...      0      0      0      0      0      0      0      0      0
4      9    0    0    0    0    0    0    0    0  ...      0      0      0      0      0      0      0      0      0

[5 rows x 785 columns]

In [46]:
df_three.shape

(60000, 785)

In [53]:
X_train2,X_test2,y_train2,y_test2 = train_test_split(df_three.iloc[:,1:],df_three.iloc[:,:1], test_size= 0.2, random_state= 42)

In [54]:
lor2 = LogisticRegression(multi_class='multinomial')

lor2.fit(X_train2,y_train2)

y_predlr2 = lor2.predict(X_test2)

C:\Users\HP Laptop 15\tfenv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP Laptop 15\tfenv\lib\site-packages\sklearn\linear_model\_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\HP Laptop 15\tfenv\lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [55]:
print(confusion_matrix(y_test2,y_predlr2))

[[1139    0    6    3    4    4    5    4    8    2]
 [   0 1283    8    6    2    3    1    2   13    4]
 [   1   18 1054   14   13    5   18   17   29    5]
 [   4    8   36 1090    1   32    2    9   22   15]
 [   4    2    5    2 1108    3    9    4    7   32]
 [  15    5   14   39    9  961   11    4   38    8]
 [  11    0   15    1    9   14 1120    2    5    0]
 [   5    7   15    9   10    2    0 1209    6   36]
 [  10   13   14   31    9   32   10    4 1028    9]
 [   5    4    5   14   28   10    0   39   14 1075]]

In [56]:
print(classification_report(y_test2,y_predlr2))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1175
           1       0.96      0.97      0.96      1322
           2       0.90      0.90      0.90      1174
           3       0.90      0.89      0.90      1219
           4       0.93      0.94      0.94      1176
           5       0.90      0.87      0.89      1104
           6       0.95      0.95      0.95      1177
           7       0.93      0.93      0.93      1299
           8       0.88      0.89      0.88      1160
           9       0.91      0.90      0.90      1194

    accuracy                           0.92     12000
   macro avg       0.92      0.92      0.92     12000
weighted avg       0.92      0.92      0.92     12000

In [57]:
dt2 = DecisionTreeClassifier()

dt2.fit(X_train2,y_train2)

y_preddt2 = dt2.predict(X_test2)

In [58]:
print(confusion_matrix(y_test2,y_preddt2))

[[1062    1   19    9    9   25   19   10    8   13]
 [   1 1265    8   10    7    7    8    3   10    3]
 [  14   11 1001   23   13    8   15   23   44   22]
 [  14   10   31 1010    8   59   10   11   34   32]
 [   4    7   14    3 1020   10   14   14   16   74]
 [  17   11    7   52   13  901   30    8   38   27]
 [  19   13   12    2   24   25 1051    4   24    3]
 [   8   13   25   19   10    4    2 1177   12   29]
 [   8   20   41   48   29   32   24   16  910   32]
 [  11   11   12   12   62   17    6   37   32  994]]

In [59]:
print(classification_report(y_test2,y_preddt2))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91      1175
           1       0.93      0.96      0.94      1322
           2       0.86      0.85      0.85      1174
           3       0.85      0.83      0.84      1219
           4       0.85      0.87      0.86      1176
           5       0.83      0.82      0.82      1104
           6       0.89      0.89      0.89      1177
           7       0.90      0.91      0.90      1299
           8       0.81      0.78      0.80      1160
           9       0.81      0.83      0.82      1194

    accuracy                           0.87     12000
   macro avg       0.86      0.86      0.86     12000
weighted avg       0.87      0.87      0.87     12000